
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.7'
	id 'io.spring.dependency-management' version '1.1.5'
	//id "io.swagger.core.v3.swagger-gradle-plugin" version "2.2.28"
}

group = 'com.project'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}
tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
	options.compilerArgs.add("-Amapstruct.defaultComponentModel=spring")
	options.compilerArgs.add("-Amapstruct.defaultInjectionStrategy=constructor")
}
dependencies {

	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	//Map Struct dependencies
	implementation("org.mapstruct:mapstruct:1.6.3")
	annotationProcessor("org.mapstruct:mapstruct-processor:1.6.3")
	//Valid Annotation
	implementation("org.springframework.boot:spring-boot-starter-validation")
	// https://mvnrepository.com/artifact/com.googlecode.libphonenumber/libphonenumber
	implementation group: 'com.googlecode.libphonenumber', name: 'libphonenumber', version: '8.13.55'
	//SWAGGER DEPENDENCY
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'
	//Apache Commons IO
	implementation 'commons-io:commons-io:2.11.0'
	//implementation('org.apache.tomcat:tomcat-catalina:10.1.16')
	implementation 'org.springframework.boot:spring-boot-starter-logging'
	implementation 'com.hazelcast.jet.contrib:hazelcast-jet-spring-boot-starter:2.0.0'
	// https://mvnrepository.com/artifact/org.liquibase/liquibase-gradle-plugin
	implementation("org.liquibase:liquibase-core:4.24.0")
	//########### CIRCUIT BREAKER #############################################
	implementation("io.github.resilience4j:resilience4j-spring-boot3:2.1.0")
	//########### Aspect Oriented Porgamming Injection ##############/////
	implementation("org.springframework.boot:spring-boot-starter-aop")
	//############ Jasper Report Library
	// https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports
	implementation("net.sf.jasperreports:jasperreports:7.0.3")
}
tasks.named('test') {
	useJUnitPlatform()
}




