spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    url: jdbc:postgresql://localhost:5432/postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
        current_session_context_class: thread
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false' #hibernate sorgularının console'da görünür olması ya da olmaması
  application:
    name: contactsdemo
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

  file:
    name: myapplication.log
